version: "3"
tasks:
  default:
    desc: Show help
    cmds:
      - task --list-all

  build-wasm:
    desc: Cargo build the wasm binary from rust
    cmds:
      - cargo build --release --target=wasm32-unknown-unknown

  compile:
    desc: Build the typescript app
    deps:
      - build-wasm
    cmds:
      - pnpm compile

  dev:
    desc: Start development with watch mode
    deps:
      - build-wasm
    cmds:
      - pnpm watch

  package:
    desc: Package the extension
    deps:
      - build-wasm
      - compile
    cmds:
      - vsce package
