[package]
name = "bininspect"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] 

[dependencies]
goblin = "0.10.0"
scroll = "0.13.0"
wit-bindgen = "0.43.0"


[package.metadata.component]
package = "bininspect:api"
